# Generated by Django 5.0.1 on 2024-05-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10, verbose_name='Cedula')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellido')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('correo', models.EmailField(max_length=50, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('sexo', models.CharField(max_length=50, verbose_name='Sexo')),
                ('nivel', models.CharField(max_length=15, verbose_name='Nivel')),
                ('fecha_nacimiento', models.DateField()),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
            ],
        ),
    ]
