# Generated by Django 5.0.1 on 2024-05-01 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catequesis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persona',
            new_name='Personaddd',
        ),
    ]
