# Generated by Django 5.0.1 on 2024-05-01 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catequesis', '0002_rename_persona_personaddd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personaddd',
            new_name='Persona',
        ),
    ]
