# Generated by Django 5.0.1 on 2024-05-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catequesis', '0003_rename_personaddd_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_grupo', models.CharField(choices=[('Inicial', 'Inicial'), ('Reconciliacion', 'Reconciliacion'), ('Eucaristia', 'Eucaristia'), ('Año Biblico', 'Año Biblico'), ('Primero Confirmacion', 'Primero Confirmacion'), ('Segundo Confirmacion', 'Segundo Confirmacion')], default='*', max_length=20, verbose_name='nom_grupo')),
                ('paralelo', models.CharField(choices=[('A', 'B'), ('C', 'D')], default='*', max_length=10, verbose_name='paralelo')),
                ('dia', models.CharField(choices=[('Viernes', 'Viernes'), ('Sabado', 'Sabado')], default='*', max_length=10, verbose_name='dia')),
                ('fecha_inicio', models.DateField(default='', null=True)),
                ('fecha_final', models.DateField(default='', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='persona',
            name='nivel',
        ),
        migrations.AddField(
            model_name='persona',
            name='rol',
            field=models.CharField(choices=[('Catequista', 'Catequista'), ('Alumno', 'Alumno')], default='*', max_length=10, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='*', max_length=50, verbose_name='Sexo'),
        ),
    ]
