# Generated by Django 5.0.1 on 2024-05-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catequesis', '0004_grupo_remove_persona_nivel_persona_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='grupo',
            field=models.ManyToManyField(related_name='Grupo', to='Catequesis.grupo'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nom_grupo',
            field=models.CharField(choices=[('Inicial', 'Inicial'), ('Reconciliacion', 'Reconciliacion'), ('Eucaristia', 'Eucaristia'), ('Año Biblico', 'Año Biblico'), ('Primero Confirmacion', 'Primero Confirmacion'), ('Segundo Confirmacion', 'Segundo Confirmacion')], default='', max_length=20, verbose_name='nom_grupo'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='paralelo',
            field=models.CharField(choices=[('A', 'B'), ('C', 'D')], default='', max_length=10, verbose_name='paralelo'),
        ),
    ]
