# Generated by Django 5.0.1 on 2024-05-24 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catequesis', '0005_persona_grupo_alter_grupo_nom_grupo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='grupo',
        ),
    ]
