# Generated by Django 5.0.1 on 2024-05-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catequesis', '0006_remove_persona_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='grupo',
            field=models.ManyToManyField(related_name='Grupo', to='Catequesis.grupo'),
        ),
    ]
