# Generated by Django 5.0.1 on 2024-05-27 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catequesis', '0009_alter_persona_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='grupo',
        ),
    ]
